version: '3.8'
services:
  reverseproxy:
    image: minhln9/udagram-reverseproxy
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - api-feed
      - api-user
  api-feed:
    image: minhln9/udagram-api-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      - POSTGRES_HOST=udagram-db-2.co3uzsllrazw.us-east-1.rds.amazonaws.com
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=mih54in2025GO!
      - POSTGRES_DB=postgres
      - AWS_BUCKET=arn:aws:s3:::udagram-images-username
      - AWS_REGION=us-east-1
      - AWS_PROFILE=default
      - JWT_SECRET=testing
      - URL=http://localhost:8100
  api-user:
    image: minhln9/udagram-api-user
    environment:
      - POSTGRES_HOST=udagram-db-2.co3uzsllrazw.us-east-1.rds.amazonaws.com
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=mih54in2025GO!
      - POSTGRES_DB=postgres
      - AWS_BUCKET=arn:aws:s3:::udagram-images-username
      - AWS_REGION=us-east-1
      - AWS_PROFILE=default
      - JWT_SECRET=testing
      - URL=http://localhost:8100
  frontend:
    image: minhln9/udagram-frontend
    ports:
      - "8100:80"