version: 2.1

orbs:
  node: circleci/node@5.0.1
  aws-cli: circleci/aws-cli@1.3.1

jobs:
  build-and-deploy:
    docker:
      - image: 'cimg/base:stable' # Base image with Node.js
    steps:
      - checkout # Clone the repository
      - node/install # Install Node.js
      - aws-cli/setup # Set up AWS CLI

      # Install frontend dependencies
      - run:
          name: Install Frontend Dependencies
          command: |
            cd udagram-frontend
            npm install

      # Build frontend
      - run:
          name: Build Frontend
          command: |
            cd udagram-frontend
            npm run build

      # Deploy frontend to S3
      - run:
          name: Deploy Frontend to S3
          command: |
            cd udagram-frontend
            aws s3 sync ./dist s3://your-frontend-bucket-name --delete

      # Install backend dependencies for `user` service
      - run:
          name: Install Backend User Dependencies
          command: |
            cd udagram-api-user
            npm install

      # Build backend user service
      - run:
          name: Build Backend User Service
          command: |
            cd udagram-api-user
            npm run build

      # Deploy backend user service to Elastic Beanstalk
      - run:
          name: Deploy Backend User to Elastic Beanstalk
          command: |
            cd udagram-api-user
            zip -r user-app.zip . -x node_modules/\* -x .git/\*
            aws elasticbeanstalk create-application-version --application-name udagram-api-user \
                --version-label user-v1 \
                --source-bundle S3Bucket="your-elastic-beanstalk-bucket",S3Key="user-app.zip"
            aws elasticbeanstalk update-environment --environment-name user-env \
                --version-label user-v1

      # Install backend dependencies for `feed` service
      - run:
          name: Install Backend Feed Dependencies
          command: |
            cd udagram-api-feed
            npm install

      # Build backend feed service
      - run:
          name: Build Backend Feed Service
          command: |
            cd udagram-api-feed
            npm run build

      # Deploy backend feed service to Elastic Beanstalk
      - run:
          name: Deploy Backend Feed to Elastic Beanstalk
          command: |
            cd udagram-api-feed
            zip -r feed-app.zip . -x node_modules/\* -x .git/\*
            aws elasticbeanstalk create-application-version --application-name udagram-api-feed \
                --version-label feed-v1 \
                --source-bundle S3Bucket="your-elastic-beanstalk-bucket",S3Key="feed-app.zip"
            aws elasticbeanstalk update-environment --environment-name feed-env \
                --version-label feed-v1

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy:
          context: aws
          filters:
            branches:
              only:
                - main
