version: 2.1

jobs:
  build_and_push:
    docker:
      - image: circleci/docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          command: |
            apk add --no-cache py3-pip
            pip3 install docker-compose
      - run:
          name: Build and Start Containers
          command: docker-compose up --build -d
      - run:
          name: Run Tests
          command: docker-compose run <test-service> npm test
      - run:
          name: Stop Containers
          command: docker-compose down
