version: 2.1

executors:
  docker-executor:
    docker:
      - image: docker:latest
    working_directory: ~/repo

jobs:
  build-and-push:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Images
          command: |
            docker-compose -f docker-compose-build.yaml build --parallel
      - run:
          name: Tag and Push API Feed Image
          command: |
            docker tag minhln9/udagram-api-feed:latest minhln9/udagram-api-feed:latest
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push minhln9/udagram-api-feed:latest
      - run:
          name: Tag and Push API User Image
          command: |
            docker tag minhln9/udagram-api-user:latest minhln9/udagram-api-user:latest
            docker push minhln9/udagram-api-user:latest
      - run:
          name: Tag and Push Frontend Image
          command: |
            docker tag minhln9/udagram-frontend:latest minhln9/udagram-frontend:latest
            docker push minhln9/udagram-frontend:latest
      - run:
          name: Tag and Push Reverse Proxy Image
          command: |
            docker tag minhln9/udagram-reverseproxy:latest minhln9/udagram-reverseproxy:latest
            docker push minhln9/udagram-reverseproxy:latest

workflows:
  version: 2
  build-and-push-workflow:
    jobs:
      - build-and-push
