version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@1.0.2

jobs:
  build_and_push:
    docker:
      - image: cimg/node:18.16.0 # Use a specific Node.js image for compatibility
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.17 # Explicitly set a compatible Docker version
      - aws-cli/setup:
          version: "2"
      - run:
          name: Install Front-End Dependencies
          command: |
            cd udagram-frontend
            npm install
      - run:
          name: Front-End Build
          command: |
            cd udagram-frontend
            npm run build
      - run:
          name: Install Back-End Dependencies (Feed Service)
          command: |
            cd udagram-api-feed
            npm install
      - run:
          name: Back-End Build (Feed Service)
          command: |
            cd udagram-api-feed
            npm run build
      - run:
          name: Install Back-End Dependencies (User Service)
          command: |
            cd udagram-api-user
            npm install
      - run:
          name: Back-End Build (User Service)
          command: |
            cd udagram-api-user
            npm run build
      - run:
          name: Build and Push Docker Images
          command: |
            docker build -t $DOCKER_USERNAME/udagram-api-feed:latest ./udagram-api-feed
            docker build -t $DOCKER_USERNAME/udagram-api-user:latest ./udagram-api-user
            docker build -t $DOCKER_USERNAME/udagram-frontend:latest ./udagram-frontend
            docker build -t $DOCKER_USERNAME/udagram-reverseproxy:latest ./udagram-reverseproxy
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push $DOCKER_USERNAME/udagram-api-feed:latest
            docker push $DOCKER_USERNAME/udagram-api-user:latest
            docker push $DOCKER_USERNAME/udagram-frontend:latest
            docker push $DOCKER_USERNAME/udagram-reverseproxy:latest

workflows:
  version: 2
  build_and_push_workflow:
    jobs:
      - build_and_push
