apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: api-user
  name: api-user
spec:
  replicas: 2
  selector:
    matchLabels:
      service: api-user  # This must match the labels in the template
  template:
    metadata:
      labels:
        service: api-user
    spec:
      containers:
      - image: minhln9/udagram-api-user:latest
        name: api-user 
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "128Mi"  # Minimum memory required
            cpu: "250m"
          limits:
            memory: "2048Mi"  # Increase memory limit
            cpu: "500m"
        env:
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: URL 
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: JWT_SECRET
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: POSTGRES_DB
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: POSTGRES_HOST
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_USERNAME
      restartPolicy: Always

